version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/en/ > docs/en/conf.py"

python:
  install:
  - requirements: docs/requirements-doc.txt
  # - method: pip
  #   path: ".[docs]"
