name: docs

on:
  pull_request:
    branches: ["dev", "v1"]
  push:
    branches: ["v1"]

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install doc dependencies
      run: |
        pip install ".[docs]"

    - name: Build documentation
      run: |
        make doc
